[project]
name = "spark-gx-pilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.1.1",
    "great-expectations>=1.6.2",
    "pyspark>=4.0.1",
    "numpy<2.0",

]
